# Generated by Django 4.0.1 on 2022-01-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date closed'),
        ),
    ]
